### ISSUE TITLE
Já funciona?

### ISSUE THREAD

**Issue by ghost** [erycson/AgarioServer#1]
o emulador já funciona?

**Comment by erycson** [comment]
Sim, mas ainda é necessário varias pequenas correções.

Versão compilada:
http://www.ragezone.com.br/showthread.php?t=96548
https://forum.ragezone.com/f857/webgame-agar-io-private-server-1064150/

**Comment by ghost** [comment]
o que já é possivel fazer? tipo: separar-se, comer outras peças.

**Comment by erycson** [comment]
Andar, separar, comer células e as comidas que ficam espalhadas no mapa, vírus estão sendo criados e se dividem quando alimentados, células separadas não se juntam, ejetar massa.

**Comment by ghost** [comment]
Obrigado!
